baseURL = "https://avian-lovelace.github.io/"
# include content marked as draft
buildDrafts = false
# include content with publishdate in the future
buildFuture = false
# include content already expired
buildExpired = false
# enable this to make all relative URLs relative to content root. Note that this does not affect absolute URLs.
relativeURLs = true
disableRSS = true
enableRobotsTXT = true
editor = "nano"
languageCode = "en"
language = "en"
theme = "vncnt-hugo"
title = "Robin Gieseking's Personal Website"

_merge = "none"

[permalinks]
  fixed = ":title/"
  posts = "posts/:slug/"

[params]
  author = "Robin Gieseking"
  description = "This is Robin Gieseking's personal website. You can check out my skills and experience on LinkedIn and some of my personal projects on GitHub."
  bio = "Full-stack Software Engineer"
  avatar = "robin-logo.svg"
  favicon = "robin-logo.svg"
  # eror404 is rendered as Markdown on error page
  error404 = """This page doesn't exist

[Return to homepage](.)"""

  [params.contact]
    # the default fontawesome style in simple key-value pairs is "fab", i.e. brand icons
    github = "https://github.com/avian-lovelace/"
    linkedin = "https://www.linkedin.com/in/robin-gieseking/"

    [params.contact.email]
      name = "email" # may be omitted. defaults to key name
      icon = "envelope" # may be omitted. defaults to key name
      style = "fas" # may be omitted. default = "fas"
      link = "mailto:robinagieseking@gmail.com"
